### PR TITLE
Use std::random_device for UUID generation

### PR DESCRIPTION
**Pull request by halvfigur**
Signed-off-by: Alexander Perlman <fixed-term.Alexander.Perlman@se.bosch.com>

### CODE REVIEW

**Comment by argerus** [comment]
Like a bosch!

**Review by JochenKienzle — CHANGES_REQUESTED** [review]
Please merge/rebase to get the integration tests running again. Then it is ready for merge :)

**Comment by halvfigur** [comment]
Merge conflicts resolved.

**Review by JochenKienzle — APPROVED** [review]
Looks good :+1:

**Pull request merged**
