### PR TITLE
Fix typo in readme file

### PR DESCRIPTION
**Pull request by JulianSchmidgall**
Just found some typo in the readme file, while reading through it.

### CODE REVIEW

**Comment by SebastianSchildt** [comment]
Thanks for fixing this.

Please note we require pull requests to be signed-off, and if I see correctly, this one isn't

You can sign off with `git commit -s -m "my commit message", or ammend your last commit with `git commit -s --amend"  (then you might need to force push). 

Signing off adds a line (you could also do so maunally) to your commit message

"Signed-off-by: name <email>"  
Basically, when you do this you agree to https://www.genivi.org/contribute, see https://github.com/GENIVI/iot-event-analytics/blob/develop/CONTRIBUTING.md#contribution-requirements

@llakie Shouldn't this have been checked automatically, by our bot (who could also post this message then ;)

**Comment by llakie** [comment]
@SebastianSchildt Actually yes. Workflow is available within the actions, but not triggered yet. I will investigate on this

**Comment by JulianSchmidgall** [comment]
Sorry for that. I hope it's fine now.

**Review by SebastianSchildt — APPROVED** [review]
Perfect 👍 
lgtm

**Pull request merged**
